### ISSUE TITLE
Parsing Flags Incorrectly

### ISSUE THREAD

**Issue by clandest1n** [ropnop/kerbrute#34]
Pulling the latest kerbrute version (untagged):
./kerbrute passwordspray --dc <ip> -d <FQDN> -output Summer2020.txt valid.txt Summer2020

Error:
You must specify a password to spray with, or --user-as-pass

**Comment by ropnop** [comment]
Ah I think I see the problem: try putting two dashes before output `--output` or just using `-o`

**Comment by clandest1n** [comment]
LOL sorry about that.
