### ISSUE TITLE
Make problem

### ISSUE THREAD

**Issue by yildirimserkan** [ropnop/kerbrute#4]
Hello. I tried making all but I got this message;
What can I do for this problem?
Thanks

@kali]─[/opt/kerbrute]
└──╼ $make all
Done.
Building for windows amd64..
main.go:4:2: cannot find package "github.com/ropnop/kerbrute/cmd" in any of:
	/usr/lib/go-1.11/src/github.com/ropnop/kerbrute/cmd (from $GOROOT)
	/home/x23_11/go/src/github.com/ropnop/kerbrute/cmd (from $GOPATH)
main.go:5:2: cannot find package "github.com/ropnop/kerbrute/util" in any of:
	/usr/lib/go-1.11/src/github.com/ropnop/kerbrute/util (from $GOROOT)
	/home/x23_11/go/src/github.com/ropnop/kerbrute/util (from $GOPATH)
Building for windows 386..
main.go:4:2: cannot find package "github.com/ropnop/kerbrute/cmd" in any of:
	/usr/lib/go-1.11/src/github.com/ropnop/kerbrute/cmd (from $GOROOT)
	/home/x23_11/go/src/github.com/ropnop/kerbrute/cmd (from $GOPATH)
main.go:5:2: cannot find package "github.com/ropnop/kerbrute/util" in any of:
	/usr/lib/go-1.11/src/github.com/ropnop/kerbrute/util (from $GOROOT)
	/home/x23_11/go/src/github.com/ropnop/kerbrute/util (from $GOPATH)
Done.
Building for linux amd64...
main.go:4:2: cannot find package "github.com/ropnop/kerbrute/cmd" in any of:
	/usr/lib/go-1.11/src/github.com/ropnop/kerbrute/cmd (from $GOROOT)
	/home/x23_11/go/src/github.com/ropnop/kerbrute/cmd (from $GOPATH)
main.go:5:2: cannot find package "github.com/ropnop/kerbrute/util" in any of:
	/usr/lib/go-1.11/src/github.com/ropnop/kerbrute/util (from $GOROOT)
	/home/x23_11/go/src/github.com/ropnop/kerbrute/util (from $GOPATH)
Building for linux 386...
main.go:4:2: cannot find package "github.com/ropnop/kerbrute/cmd" in any of:
	/usr/lib/go-1.11/src/github.com/ropnop/kerbrute/cmd (from $GOROOT)
	/home/x23_11/go/src/github.com/ropnop/kerbrute/cmd (from $GOPATH)
main.go:5:2: cannot find package "github.com/ropnop/kerbrute/util" in any of:
	/usr/lib/go-1.11/src/github.com/ropnop/kerbrute/util (from $GOROOT)
	/home/x23_11/go/src/github.com/ropnop/kerbrute/util (from $GOPATH)
Done.
Building for mac amd64...
main.go:4:2: cannot find package "github.com/ropnop/kerbrute/cmd" in any of:
	/usr/lib/go-1.11/src/github.com/ropnop/kerbrute/cmd (from $GOROOT)
	/home/x23_11/go/src/github.com/ropnop/kerbrute/cmd (from $GOPATH)
main.go:5:2: cannot find package "github.com/ropnop/kerbrute/util" in any of:
	/usr/lib/go-1.11/src/github.com/ropnop/kerbrute/util (from $GOROOT)
	/home/x23_11/go/src/github.com/ropnop/kerbrute/util (from $GOPATH)
Building for mac 386...
main.go:4:2: cannot find package "github.com/ropnop/kerbrute/cmd" in any of:
	/usr/lib/go-1.11/src/github.com/ropnop/kerbrute/cmd (from $GOROOT)
	/home/x23_11/go/src/github.com/ropnop/kerbrute/cmd (from $GOPATH)
main.go:5:2: cannot find package "github.com/ropnop/kerbrute/util" in any of:
	/usr/lib/go-1.11/src/github.com/ropnop/kerbrute/util (from $GOROOT)
	/home/x23_11/go/src/github.com/ropnop/kerbrute/util (from $GOPATH)
Done.

**Comment by ropnop** [comment]
Hi! Go is very opinionated about its paths, so before running the Make command, you need to ensure the code is in your $GOPATH and the path matches the repository.

Try cloning the repo to `/home/x23_11/go/src/github.com/ropnop/kerbrute` and running the make command again - that should do the trick.

You could also run `go get github.com/ropnop/kerbrute` which will clone the project to the right directory for you as well as a first step.

Let me know if that works for you!

**Comment by ropnop** [comment]
Closing this. Let me know if you still have any problems!

**Comment by thunderki78** [comment]
Hi,
hen typing "go get github.com/ropnop/kerbrute"
i'm getting a lot of error like
```
/root/go/src/github.com/spf13/cobra/bash_completions.go:22:24: error: reference to undefined identifier \u2018io.StringWriter\u2019
 func writePreamble(buf io.StringWriter, name string) {
```
Could you help please?
