### ISSUE TITLE
Expired passwords are treated as failures

### ISSUE THREAD

**Issue by docsmooth** [ropnop/kerbrute#8]
Root cause: KDC_Error] KDC_Error: AS Exchange Error: kerberos error response from KDC: KRB Error: (23) KDC_ERR_KEY_EXPIRED Password has expired; change password to reset

KRBERR_KEY_EXPIRED should be treated as  a success - appears to be that in session/session.go:TestLogin you're treating all errors as failures:
    if err != nil {
        return false, err
    }

I think 23 should be a success? or configurable as success?

**Comment by ropnop** [comment]
Thanks for reporting - interesting case I hadn't considered.

It's definitely an error I can handle better - but I don't think it's as simple as treating it as a success either. From what I can tell, if the user's password is expired - ANY password will result in this KDC error. If we treated it as a success you'd get a lot of "false positives" thinking you got a valid login when you really don't.

One thing that may be possible is when that error is encountered is to attempt a password reset with the current password guess. I don't want this tool to actually change or reset any passwords, so I'll have to see if there's a way to "test" it and then abort before a reset actually happens.

**Comment by ropnop** [comment]
Okay nevermind - it does only give that error if the password is correct. I was testing against a user who had pre-auth disabled (another edge case to deal with). I'll cut a new branch to handle both cases

**Comment by ropnop** [comment]
Fixed in #12 

I'll cut a new release shortly with this fix. Thanks!
